In [1]:
import torch
from torch.nn.functional import one_hot
import numpy as np
from sklearn.metrics.pairwise import rbf_kernel

inputs = torch.load("tests/inputs.pt")
labels = torch.load("tests/labels.pt")

In [2]:
from scipy import linalg
from numpy import linalg as LA
from scipy.spatial.distance import cdist

def RBF(x, sigma):
    distance = torch.cdist(x, x)
    return torch.exp(-(1/(sigma**2)) * (distance**2))

labels_oh = one_hot(labels, num_classes=10).float()
labels_test = labels.reshape((len(labels), 1)).float()

In [63]:


test = labels_test
A = RBF(test, 0.1) / (len(test))
print(A)
# w = linalg.eigh(A, eigvals_only=True)
# print(w)
# print(w[40:])

# length=5
# for idx in range(150):
#     start = idx*length
#     end = start+length
#     test = labels_oh[start:end]
#     print(test)
#     A = RBF(test, 0.01) / 6000
#     w = linalg.eigh(A, eigvals_only=True)
#     print(w)

[[1.00000000e-002 0.00000000e+000 3.72007598e-046 ... 0.00000000e+000
  1.91516960e-176 0.00000000e+000]
 [0.00000000e+000 1.00000000e-002 0.00000000e+000 ... 0.00000000e+000
  0.00000000e+000 3.72007598e-046]
 [3.72007598e-046 0.00000000e+000 1.00000000e-002 ... 0.00000000e+000
  3.72007598e-046 0.00000000e+000]
 ...
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 1.00000000e-002
  0.00000000e+000 0.00000000e+000]
 [1.91516960e-176 0.00000000e+000 3.72007598e-046 ... 0.00000000e+000
  1.00000000e-002 1.91516960e-176]
 [0.00000000e+000 3.72007598e-046 0.00000000e+000 ... 0.00000000e+000
  1.91516960e-176 1.00000000e-002]]


# Caso 1

In [3]:
test = labels_oh[12*5:(12*5)+5]
print(test)

A = RBF(test, 0.01)
print(A)
print(np.linalg.det(A.cpu()))

w = linalg.eigh(A.cpu(), eigvals_only=True)
print(w)

tensor([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]], device=&#39;cuda:0&#39;)
tensor([[1., 1., 0., 0., 1.],
        [1., 1., 0., 0., 1.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [1., 1., 0., 0., 1.]], device=&#39;cuda:0&#39;)
0.0
[-1.5065224e-07  3.1442951e-08  1.0000000e+00  1.0000000e+00
  3.0000000e+00]


In [4]:
test = labels_test[6:12]
distance = torch.cdist(test, test)
print(distance)
# A = RBF(test, 0.01)
# print(A)
# print(test)
# print(np.linalg.det(A.cpu()))
# w = linalg.eigh(A.cpu(), eigvals_only=True)
# print(w)

tensor([[0., 2., 0., 3., 2., 4.],
        [2., 0., 2., 1., 0., 2.],
        [0., 2., 0., 3., 2., 4.],
        [3., 1., 3., 0., 1., 1.],
        [2., 0., 2., 1., 0., 2.],
        [4., 2., 4., 1., 2., 0.]], device=&#39;cuda:0&#39;)


In [5]:
test = labels_oh[6:12]
distance = torch.cdist(test, test)
print(distance)
A = RBF(test, 0.01)
print(A)

tensor([[0.0000, 1.4142, 0.0000, 1.4142, 1.4142, 1.4142],
        [1.4142, 0.0000, 1.4142, 1.4142, 0.0000, 1.4142],
        [0.0000, 1.4142, 0.0000, 1.4142, 1.4142, 1.4142],
        [1.4142, 1.4142, 1.4142, 0.0000, 1.4142, 1.4142],
        [1.4142, 0.0000, 1.4142, 1.4142, 0.0000, 1.4142],
        [1.4142, 1.4142, 1.4142, 1.4142, 1.4142, 0.0000]], device=&#39;cuda:0&#39;)
tensor([[1., 0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 1., 0.],
        [1., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]], device=&#39;cuda:0&#39;)


# Caso 2

In [6]:
test = labels_oh[7:13]
print(test)

A = RBF(test, 0.01) / len(test)
print(A)
w = linalg.eigh(A, eigvals_only=True)
print(w)

tensor([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]], device=&#39;cuda:0&#39;)
tensor([[0.1667, 0.0000, 0.0000, 0.1667, 0.0000, 0.1667],
        [0.0000, 0.1667, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.1667, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.0000, 0.0000, 0.1667, 0.0000, 0.1667],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.1667, 0.0000],
        [0.1667, 0.0000, 0.0000, 0.1667, 0.0000, 0.1667]], device=&#39;cuda:0&#39;)


TypeError: can&#39;t convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

# Caso sintetico

In [ ]:
test = torch.tensor([[1,0,0], [0,0,1], [0,0,1], [1,0,0], [0,0,1],[0,0,1]]).float()
A = RBF(test, 0.1)/2000

non_diagonal = np.where(~np.eye(A.shape[0],dtype=bool))
# A[non_diagonal] += 1e-36
print(A)
w = linalg.eigh(A, eigvals_only=True)
print(w)

In [ ]:
np.log2(10)

In [ ]:
torch.exp(-torch.tensor([100]).float())

In [11]:
def applyNoise(labels, noise_factor=1e-3):
    labels_cp = labels.clone()
    noise = torch.rand(labels.shape).cuda()
    noise = noise/(torch.sum(noise)*(1/noise_factor))
    labels_cp += noise

    labels_cp[torch.where(labels_cp >= 1)] -= noise_factor
    return labels_cp

test = labels_oh[12*5:(12*5)+5]
test = applyNoise(test)
print(test)
print(torch.sum(test,dim=1))

A = rbf_kernel(test.cpu(), test.cpu(), gamma=1/(2*(0.1**2)))
print(A)

w = linalg.eigh(A, eigvals_only=True)
print(w)

tensor([[2.5733e-06, 2.6307e-05, 3.2719e-05, 2.8114e-05, 9.9901e-01, 3.2010e-05,
         1.8710e-05, 2.4210e-05, 4.0101e-06, 3.3827e-05],
        [2.7135e-05, 3.6212e-05, 5.4944e-06, 3.3884e-05, 9.9903e-01, 2.6277e-05,
         2.5370e-05, 2.5408e-05, 2.7867e-05, 2.2277e-05],
        [9.7411e-06, 2.9726e-06, 9.3139e-08, 2.7484e-05, 2.8640e-05, 1.8558e-05,
         9.9901e-01, 1.0269e-05, 4.4821e-07, 2.7556e-05],
        [9.9902e-01, 1.6369e-05, 2.3083e-05, 1.2738e-05, 3.2746e-05, 2.8227e-05,
         1.5223e-06, 2.1855e-05, 2.9091e-05, 3.1146e-05],
        [3.7161e-05, 3.6086e-05, 9.5493e-06, 3.4605e-05, 9.9902e-01, 1.0792e-06,
         2.3144e-05, 1.2508e-05, 4.0863e-07, 3.7403e-06]], device=&#39;cuda:0&#39;)
tensor([0.9992, 0.9993, 0.9991, 0.9992, 0.9992], device=&#39;cuda:0&#39;)
[[1.0000000e+00 9.9999994e-01 4.6242849e-44 4.4841551e-44 9.9999988e-01]
 [9.9999994e-01 1.0000000e+00 4.4841551e-44 4.4841551e-44 9.9999994e-01]
 [4.6242849e-44 4.4841551e-44 1.0000000e+00 4.4841551e-44 4

In [12]:
def testingEigenvaluesComputation(data):
    for impl in [np.linalg.eig, np.linalg.eigh, LA.eig, LA.eigh]:
        print("My RBF")

        A = (RBF(test, 0.1) / len(test)).numpy()
        w, v = impl(A) 
        print(np.sort(w))
        reconstructed = np.dot(v * w, v.conj().T)
        print("Allclose:", np.allclose(reconstructed, A), '\n')
        print("---"*3)

        print("Scikit-learn's RBF")
        A = rbf_kernel(test.cpu(), test.cpu(), gamma=(-1/(0.1**2))) / len(test)
        w, v = impl(A)
        print(np.sort(w))
        reconstructed = np.dot(v * w, v.conj().T)
        print("Allclose:", np.allclose(reconstructed, A), '\n\n\n')

In [32]:
# from numpy import linalg as LA
# https://stackoverflow.com/questions/36819739/scipy-eigh-gives-negative-eigenvalues-for-positive-semidefinite-matrix Take a look
from scipy import linalg as LA

length=30
n_iter = (int)(len(labels)/length)


for idx in range(n_iter):
    print("Test {}\n".format(idx))
    start = idx*length
    end = start+length
    if start > len(labels_oh):
        break 

    test = labels_oh[start:end]
    test = applyNoise(test, noise_factor=1e3)
    # print(test)
    print(np.linalg.matrix_rank(test.cpu().numpy()))

    for impl in [np.linalg.eig, np.linalg.eigh, LA.eig, LA.eigh]:
        print(impl)
        print("My RBF")

        A = RBF(test, 0.1) / len(test)
        w_0, v = impl(A.cpu()) 
        print(np.sort(w_0))
        reconstructed = np.dot(v * w_0, v.conj().T)
        print("Allclose:", np.allclose(reconstructed, A.cpu()), '\n')
        print("---"*3)

        print("Scikit-learn's RBF")
        A = rbf_kernel(test.cpu(), test.cpu(), gamma=(1/(0.1**2))) / len(test)
        w_1, v = impl(A)
        print(np.sort(w_1))
        reconstructed = np.dot(v * w_1, v.conj().T)
        print("Allclose:", np.allclose(reconstructed, A), '\n\n\n')
    
    break

Test 0

10
&lt;function eig at 0x7f9ef9cd78c0&gt;
My RBF
[1.4012985e-45 1.4012985e-45 1.4012985e-45 1.4012985e-45 3.3333335e-02
 3.3333335e-02 3.3333335e-02 3.3333335e-02 3.3333335e-02 3.3333335e-02
 3.3333335e-02 3.3333335e-02 3.3333335e-02 3.3333335e-02 3.3333335e-02
 3.3333335e-02 3.3333335e-02 3.3333335e-02 3.3333335e-02 3.3333335e-02
 3.3333335e-02 3.3333335e-02 3.3333335e-02 3.3333335e-02 3.3333335e-02
 3.3333335e-02 3.3333335e-02 3.3333335e-02 3.3333335e-02 3.3333335e-02]
Allclose: True 

---------
Scikit-learn&#39;s RBF
[0.03333332 0.03333333 0.03333334 0.03333334 0.03333334 0.03333334
 0.03333334 0.03333334 0.03333334 0.03333334 0.03333334 0.03333334
 0.03333334 0.03333334 0.03333334 0.03333334 0.03333334 0.03333334
 0.03333334 0.03333334 0.03333334 0.03333334 0.03333334 0.03333334
 0.03333334 0.03333334 0.03333334 0.03333334 0.03333334 0.03333334]
Allclose: True 



&lt;function eigh at 0x7f9ef9cd7a70&gt;
My RBF
[1.4012985e-45 1.4012985e-45 1.4012985e-45 1.4012985e-45 3.33333

In [16]:
test = labels_oh[60:90]
test = applyNoise(test, 0.1)
print(test)
A_1 = RBF(test, 0.1)
A_2 = rbf_kernel(test.cpu(), test.cpu(), gamma=1/(0.1**2) )

if np.allclose(A_1.cpu().numpy().astype(np.float64), A_2.astype(np.float64)):
    print("Ambas implementaciones dan el mismo resultado")
else:
    print("Los kernels no dan el mismo resultado")

A = A_1.cpu().numpy()
# A = A_2
# print(A)

for impl in [np.linalg.eig, np.linalg.eigh, LA.eig, LA.eigh]:
    w, v = impl(A)
    print(np.sort(w))
    reconstructed = np.dot(v * w, v.conj().T)
    print("Allclose:", np.allclose(reconstructed, A), '\n')

tensor([[5.9298e-05, 5.8598e-04, 6.4573e-04, 1.4035e-04, 9.0024e-01, 4.5300e-04,
         7.8233e-05, 6.4281e-04, 1.4221e-04, 4.6531e-04],
        [1.6451e-05, 5.5122e-04, 3.0966e-05, 2.3976e-04, 9.0041e-01, 4.4524e-05,
         4.0935e-04, 2.8034e-04, 3.8389e-04, 5.8039e-04],
        [6.0775e-04, 5.0877e-04, 2.4663e-04, 1.8725e-04, 4.8544e-04, 3.8478e-04,
         9.0005e-01, 2.5185e-04, 5.1361e-04, 2.7664e-04],
        [9.0055e-01, 3.4731e-05, 3.1741e-04, 5.0321e-04, 2.8460e-05, 1.0804e-04,
         5.9840e-04, 4.9223e-04, 4.6402e-04, 1.4343e-04],
        [8.7881e-05, 3.4592e-04, 4.3869e-04, 3.7832e-04, 9.0030e-01, 2.4914e-04,
         5.6799e-04, 6.9193e-05, 5.5812e-04, 1.8854e-04],
        [1.9141e-04, 4.4549e-04, 8.8108e-05, 5.0148e-04, 3.5250e-04, 9.0022e-01,
         1.1671e-04, 2.3328e-04, 1.3959e-04, 4.6515e-04],
        [5.5613e-04, 2.5653e-04, 1.1582e-05, 5.6624e-04, 2.8845e-04, 3.0497e-04,
         9.0047e-01, 1.0449e-04, 4.1822e-04, 7.5200e-05],
        [9.1003e-05, 9.0056

In [341]:
def hess_R(x):
    d = len(x)
    H = np.ones(d*d).reshape(d,d) / (1 - np.sum(x))**2
    H = H + np.diag(1 / (x**2))
    return H.astype(np.float64)

x = np.array([  9.98510710e-02 ,  9.00148922e-01 ,  4.41547488e-10])
A = hess_R(x)
# w,v = LA.eigh(A)
# print(w)

for impl in [np.linalg.eig, np.linalg.eigh, LA.eig, LA.eigh]:
        w, v = impl(A)
        print(np.sort(w))
        reconstructed = np.dot(v * w, v.conj().T)
        print("Allclose:", np.allclose(reconstructed, A), '\n')

[-3.01441754e+02  4.62855397e+16  5.15260753e+18]
Allclose: True 

[-1.52826050e+02  4.62855397e+16  5.15260753e+18]
Allclose: True 

[-3.01441754e+02+0.j  4.62855397e+16+0.j  5.15260753e+18+0.j]
Allclose: True 

[-1.98000004e+02  4.62855397e+16  5.15260753e+18]
Allclose: True 



In [13]:
from scipy.spatial import distance


print(distance.cosine([1, 0, 0], [0, 1, 1]))
print(distance.hamming([0, 1, 0], [0, 0, 1]))
print(distance.jaccard([0, 1, 0], [0, 0, 0]))

1.0
0.6666666666666666
1.0


In [26]:
print(distance.cosine([0,1],[1,1]))
print(distance.cosine([1],[3]))

0.29289321881345254
0.0


In [85]:
from scipy.spatial import distance

labels_changed = labels_test + 1
test = np.unpackbits(labels_changed[:5].cpu().type(torch.uint8), axis=1) 
test = test[:, -4:]
# print(test)
print(test[:5])
print(distance.cdist(test, test, metric='cosine'))
print(distance.cdist(test, test, metric='mahalanobis')) 

[[0 1 1 0]
 [0 0 0 1]
 [0 1 0 1]
 [0 0 1 0]
 [1 0 1 0]]
[[2.22044605e-16 1.00000000e+00 5.00000000e-01 2.92893219e-01
  5.00000000e-01]
 [1.00000000e+00 0.00000000e+00 2.92893219e-01 1.00000000e+00
  1.00000000e+00]
 [5.00000000e-01 2.92893219e-01 2.22044605e-16 1.00000000e+00
  1.00000000e+00]
 [2.92893219e-01 1.00000000e+00 1.00000000e+00 0.00000000e+00
  2.92893219e-01]
 [5.00000000e-01 1.00000000e+00 1.00000000e+00 2.92893219e-01
  2.22044605e-16]]
[[0.         2.91547595 2.         2.12132034 2.80624304]
 [2.91547595 0.         2.12132034 2.         2.37170825]
 [2.         2.12132034 0.         2.91547595 2.37170825]
 [2.12132034 2.         2.91547595 0.         2.80624304]
 [2.80624304 2.37170825 2.37170825 2.80624304 0.        ]]


In [24]:
labels_test[:10]

tensor([[5.],
        [0.],
        [4.],
        [1.],
        [9.],
        [2.],
        [1.],
        [3.],
        [1.],
        [4.]], device=&#39;cuda:0&#39;)

In [83]:
from scipy.spatial import distance

def RBF_labels(x, sigma):
    distance_x = distance.cdist(x, x, metric='mahalanobis')
    return np.exp(-(1/(sigma**2)) * (distance_x**2))

# labels_changed = labels_test + 1
# test = np.unpackbits(labels_changed[:9].cpu().type(torch.uint8), axis=1) 
# test = test[:, -4:]
test = labels_oh[:10].cpu().numpy()

A = RBF_labels(test, 0.1) / len(test)
w, v = np.linalg.eigh(A)
print(w)

LinAlgError: Singular matrix

In [77]:
def applyNoise(labels, noise_factor=1e-4):
    labels_cp = labels.clone()
    # noise = torch.rand(labels.shape).cuda()
    noise = torch.tensor(np.random.rand(labels.shape[0], labels.shape[1])).cuda()
    noise = noise/(torch.sum(noise)*(1/noise_factor))
    labels_cp += noise

    labels_cp[torch.where(labels_cp >= 1)] -= noise_factor
    return noise

test = labels_oh[:25]
test = applyNoise(test)
A = RBF(test, 2.100)
print(A.shape)
print(np.linalg.matrix_rank(A.cpu().numpy()))

torch.Size([25, 25])
10


In [95]:
test = labels_oh[:10]
dist = torch.norm(test[:, None] - test, dim=2)
sigma = torch.sort(dist)[0][:, :50].mean()
print(sigma)
k_l = torch.exp(-dist ** 2 / (torch.tensor(0.1) ** 2)) / dist.size(0)
print(k_l)

tensor(1.1597, device=&#39;cuda:0&#39;)
tensor([[0.1000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.1000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.1000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.1000],
        [0.0000, 0.0000, 0.0000, 0.1000, 0.0000, 0.0000, 0.1000, 0.0000, 0.1000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.1000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.1000, 0.0000, 0.0000, 0.1000, 0.0000, 0.1000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.1000, 0.0000, 0.0000, 0.1000, 0.0000, 0.1000,
         0.0000],
        [0.0000, 0.0000, 0.1000, 0.0000, 0.0000, 0.0000, 0.0000, 0.00