In [2]:
import torch

In [3]:
a = torch.rand((4,1,3,3), dtype=torch.float32)
b = torch.zeros((4,3), dtype=torch.float32)
b[0,1] = 1; b[1,2] = 1; b[2,0] = 1; b[3,0] = 1

print(a)
print(b)

tensor([[[[0.8534, 0.8146, 0.7766],
          [0.2181, 0.1874, 0.8970],
          [0.1465, 0.9920, 0.0850]]],


        [[[0.3299, 0.3058, 0.4199],
          [0.6416, 0.8732, 0.2772],
          [0.2479, 0.0907, 0.1181]]],


        [[[0.3180, 0.2701, 0.6243],
          [0.8261, 0.4445, 0.0319],
          [0.0382, 0.6680, 0.7375]]],


        [[[0.9917, 0.7217, 0.1761],
          [0.7214, 0.2656, 0.6779],
          [0.0600, 0.7625, 0.2036]]]])
tensor([[0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.],
        [1., 0., 0.]])


In [29]:
a_flatten = torch.flatten(a, 1)

# Tensor kernels definitions

def RBF(x, y, sigma):
    distance = torch.dist(x,y)
    return torch.exp(-(distance**2)/(sigma**2))

def RBF_2(x, sigma):
    distance = torch.cdist(x, x)
    return torch.exp(-(distance**2)/(sigma**2))

# Ambas funciones dan el mismo resultado, lo doy por bueno


In [30]:
rbf_a = RBF_2(a_flatten, 8)
rbf_b = RBF_2(b, 0.9)

print(rbf_a)
print(rbf_b)
print(1.5868*1.5868)

tensor([[-0.0000, -2.5180, -2.3333, -0.7701],
        [-2.5180, -0.0000, -1.0821, -1.7004],
        [-2.3333, -1.0821, -0.0000, -1.6133],
        [-0.7701, -1.7004, -1.6133, -0.0000]])
tensor([[-0.0000, -2.0000, -2.0000, -2.0000],
        [-2.0000, -0.0000, -2.0000, -2.0000],
        [-2.0000, -2.0000, -0.0000, -0.0000],
        [-2.0000, -2.0000, -0.0000, -0.0000]])
tensor([[1.0000, 0.9614, 0.9642, 0.9880],
        [0.9614, 1.0000, 0.9832, 0.9738],
        [0.9642, 0.9832, 1.0000, 0.9751],
        [0.9880, 0.9738, 0.9751, 1.0000]])
tensor([[1.0000, 0.0847, 0.0847, 0.0847],
        [0.0847, 1.0000, 0.0847, 0.0847],
        [0.0847, 0.0847, 1.0000, 1.0000],
        [0.0847, 0.0847, 1.0000, 1.0000]])
2.5179342399999998


In [15]:
k_0 = torch.zeros((len(a_flatten), len(a_flatten)))
for i in range(len(a_flatten)):
    for j in range(len(a_flatten)):
        k_0[i,j] = RBF(a_flatten[i], a_flatten[j], 8)
        
print(k_0)

tensor([[1.0000, 0.9614, 0.9642, 0.9880],
        [0.9614, 1.0000, 0.9832, 0.9738],
        [0.9642, 0.9832, 1.0000, 0.9751],
        [0.9880, 0.9738, 0.9751, 1.0000]])


In [33]:
k_1 = torch.zeros((len(b), len(b)))
for i in range(len(b)):
    for j in range(len(b)):
        k_1[i,j] = RBF(b[i], b[j], 0.1)
        
print(k_1)

tensor([[0.0000, 1.4142, 1.4142, 1.4142],
        [1.4142, 0.0000, 1.4142, 1.4142],
        [1.4142, 1.4142, 0.0000, 0.0000],
        [1.4142, 1.4142, 0.0000, 0.0000]])


In [16]:
def kernelAligmentLoss(x, y):
    return (torch.sum(x*y))/(torch.norm(x) * torch.norm(y))

In [21]:
kernelAligmentLoss(rbf_a, rbf_b)

tensor(0.7008)

In [245]:
a = torch.tensor([torch.dist(a_flatten[i-1], a_flatten[i]) for i in range(1, len(a_flatten))])
print(a)

tensor([0.9835, 0.7540, 1.4057])


In [240]:
p = [q.index(v) if v in q else 99999 for v in range(1)]

NameError: name 'q' is not defined